apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
        - name: world-service
          image: zirconblue.azurecr.io/world-service:latest
          ports:
            - containerPort: 5039

---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  selector:
    app: world-service
  ports:
    - protocol: TCP
      port: 5039
      targetPort: 5039
  type: LoadBalancer


  #